### PR TITLE
 Convert django-geoexplorer to django-geoexplorer-worldmap for layer details page

### PR DESCRIPTION
**Pull request by camp-zju**
1. Add the function layer_detail_wm in the wm_extra/views.py;
2. Add the urlpatterns of layer_detail_wm in the wm_extra/urls.py;
3. Add two templates layer_detail and layer_include which will be replaced by the templates in geonode-project.

### CODE REVIEW

**Comment by capooti** [comment]
@Niran814804102 

I am not sure what exactly this PR is doing. Please could you kindly answer to the following questions providing more details:

1) why do you need to customize layer_detail.html in GeoNode? What is the purpose? Can't this be done in the CAMP project instead than in GeoNode?

2) why do we need the layer_include.html file?

3) the way you changed urls.py does not make sense to me. Please explain in details why you need to change the file in this way.

4) why do we need a layer_detail_wm view?

Thanks in advance!

**Comment by camp-zju** [comment]
There is a commit named 'Copy some templates from geonode/wm_extra' in the cga-harvard/geonode-project/camp-2.7.x-paolo which need to be applied when you test the PR in your test server. In this commit, we copied and changed layer_detail.html and layer_include.html from wm_extra/templates/layers to geonode-project/camp/template/lwm_extra/layers.

1. why do you need to customize layer_detail.html in GeoNode? What is the purpose? Can't this be done in the CAMP project instead than in GeoNode?
I found the way to convert the django-explorer to django-explorer-worldmap for layer detail page is similar with that for map detail page. To do this for map detail page, there is a function map_detail_wm using the function gxp2wm in wm_extra/views.py, and a urlpattern to use this function map_detail_wm in wm_extra/urls.py
`url(r'^maps/(?P<mapid>[^/]+)$', map_detail_wm, name='map_detail_wm')`
and there are also two templates map_detail.html and map_include.html used by the function map_detail_wm.
To keep consistent with the process for map_detail_wm, I also tried to create an function named layer_detail_wm, a url patterns and two templates layer_detail.html and layer_include.html. As we known, we can do this two templates in CAMP project not in GeoNode, but I still want to add the two templates of layers in GeoNode like the two templates of maps. You can removed them as you can anyway.

2. why do we need the layer_include.html file?
You can also remove it since it will be replaced by the same template in CAMP project. The template layer_include.html is a copy of map_include.html.  What's more, we need the change the argument from 'config' to 'viewer' which responsed by the function layer_detail_wm.
qq 20181010094305
3. the way you changed urls.py does not make sense to me. Please explain in details why you need to change the file in this way.
There are two aspects of modification in urls.py. Ones is to add the url pattern of layer_detail_wm:
`url(r'^layers/(?P<layername>[^/]*)$', layer_detail_wm, name="layer_detail_wm"),`
And the another is to replace the url regex '^layers/(?P<layername>[^/]*)/' with regex '^layers/(?P<layername>geonode:[^/]*)$' and to replacing the url regex ^maps/(?P<mapid>[^/]+)$' with regex '^maps/(?P<mapid>\d+)$'.  I did the second aspect of modification to try to solve the wrong match when accessing the url 'maps/add_endpoint' and 'layers/upload'. You can replicate the wrong match by applying the first aspect of modification in urls.py and accessing the url 'layers/upload' in blowser.

**Comment by capooti** [comment]
dear @Niran814804102 I will work on this and introduce the WorldMap geoexplorer viewer in the layer details page following the GeoNode standard approach using hooksets (you can look at it in geonode.client). Thanks anyway for this effort!

**Comment by capooti** [comment]
Sure: https://github.com/GeoNode/geonode/tree/master/geonode/client
If you have time to work on it, that would be great! Otherwise I will to do this in a few days. Currently I am syncing worldmap-geonode to GeoNode 2.10

**Pull request closed without merging**
